import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import "@/src/app/globals.css";
import { Providers } from "@/src/app/redux/provider";
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Eusoff Hall",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
